services:
  opentsdb:
    image: petergrace/opentsdb-docker
    container_name: opentsdb-trepel
    ports:
      - "4242:4242"
    networks:
      - monitoring
    environment:
      - TSD_HTTP_ENABLED=true
      - TSD_HTTP_PORT=4242
      - TSD_STORAGE_HBASE=true
      - TSD_STORAGE_HBASE_ZK_QUORUM=zookeeper:2181
  grafana:
    image: grafana/grafana-oss:10.2.1
    container_name: grafana-trepel
    ports:
      - "3000:3000"
    depends_on:
      - opentsdb
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_DEFAULT_THEME=light      
networks:
  monitoring:
    driver: bridge
