{
 "title": "OVERVIEW",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "РАБОТА",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "motor.ctl",
     "tags": { "item_id": "*" }
    }
   ]
  },
  { "title": "ЖУРНАЛ", "type": "annolist", "gridPos": { "h": 23, "w": 9, "x": 15, "y": 0 } },
  {
   "title": "ТЕМПЕРАТУРЫ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zone_11.t",
     "tags": { "item_id": "*" }
    }
   ]
  },
  {
   "title": "ВЛАЖНОСТЬ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 8 },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "zone_11.humidity" }
   ]
  },
  {
   "title": "ЧП",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "motor.fq",
     "tags": { "item_id": "*" }
    }
   ]
  }
 ]
}